apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cts-pkasolver
  name: cts-pkasolver
  namespace: qed-kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-pkasolver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cts-pkasolver
    spec:
      containers:
      - name: cts-pkasolver
        image: ghcr.io/quanted/cts-pkasolver:main-02262389e0f84915585b92333dea5333c50ba443
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
