apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cts-pkasolver-nginx
  name: cts-pkasolver-nginx
  namespace: qed-kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-pkasolver-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cts-pkasolver-nginx
    spec:
      containers:
        - image: ghcr.io/quanted/cts-pkasolver-nginx:main-8a82104cbfd3bf39f07cb51085997973b624fdf6
          imagePullPolicy: Always
          name: cts-pkasolver-nginx
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "500Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 443
            - containerPort: 80
      restartPolicy: Always
