version: "3.1"

services:

  cts-pkasolver:
    image: ghcr.io/quanted/cts-pkasolver:main-9cfd6fd67e6de631772d580fc671e69573ba2526
    container_name: cts-pkasolver
    volumes:
      - ../:/src
    expose:
      - "8080"

  cts-pkasolver-nginx:
    image: ghcr.io/quanted/cts-pkasolver-nginx:main-8a82104cbfd3bf39f07cb51085997973b624fdf6
    container_name: cts-pkasolver-nginx
    ports:
      - "8181:80"
    links:
      - cts-pkasolver:cts-pkasolver